apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-editor-sa
  namespace: image-editor
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::642375200181:role/image-editor-eks-ecr-access