apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-editor-backend
  namespace: image-editor
  labels:
    app: image-editor-backend
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-editor-backend
  template:
    metadata:
      labels:
        app: image-editor-backend
        component: backend
    spec:
      containers:
      - name: backend
        image: 642375200181.dkr.ecr.us-east-1.amazonaws.com/image-editor-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: image-editor-backend
  namespace: image-editor
  labels:
    app: image-editor-backend
spec:
  type: ClusterIP
  selector:
    app: image-editor-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http